import Head from 'next/head'

import { useState, createContext } from 'react'
import Header from '../header'
import Footer from '../footer'
import { AppContextType } from '../../types'

export const AppContext = createContext<AppContextType>(null)

export default function Layout({ children }: { children: React.ReactNode }) {
  const [isDark, setIsDark] = useState<boolean>(true)

  const context = { isDark, setIsDark }

  return (
    <AppContext.Provider value={context}>
      <div className='flex flex-col h-screen'>
        <Head>
          <title>Countries api</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        {children}
        <Footer />
      </div>
    </AppContext.Provider>
  )
}