import Head from 'next/head'

import { createContext, ReactNode, useState } from 'react'
import Header from '../header'
import MainTag from '../mainTag'
import Footer from '../footer'
import { IContext, REGIONS } from '../../types'

export const AppContext = createContext<IContext>({} as IContext)

export default function Layout({ children }: { children: ReactNode }) {
  const [isDark, setIsDark] = useState<boolean>(true)
  const [region, setRegion] = useState<REGIONS>(REGIONS.ALL)
  const [searchQuery, setSearchQuery] = useState<string>('')
  const context = {
    isDark,
    setIsDark,
    region,
    setRegion,
    searchQuery,
    setSearchQuery
  }

  return (
    <AppContext.Provider value={context}>
      <div className='flex flex-col h-screen'>
        <Head>
          <title>Countries api</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <MainTag>
          {children}
        </MainTag>
        <Footer />
      </div>
    </AppContext.Provider>
  )
}