import Head from 'next/head'

import { ReactNode } from 'react'
import { AppProvider } from '../../context'
import Header from '../header'
import MainTag from '../mainTag'
import Footer from '../footer'

const Layout = ({ children }: { children: ReactNode }) => {
  return (
    <AppProvider>
      <div className='flex flex-col h-screen'>
        <Head>
          <title>Countries api</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <MainTag>
          {children}
        </MainTag>
        <Footer />
      </div>
    </AppProvider>
  )
}

export default Layout