import { useAppContext } from '../../hooks/useAppContext'

export default function Footer() {
  const context = useAppContext()
  const year = new Date().getFullYear()
  const bgTextClasses = `${context?.isDark && 'bg-dark-blue text-very-light-gray'} ||
                         ${!context?.isDark && 'bg-slate-100 text-very-dark-blue-lm'}`

  return (
    <footer
      className={`${bgTextClasses} flex flex-col justify-center items-center px-5 py-2`}
    >
      <p className='text-xl'>
        {`Generated by create next app. ${year}`}
      </p>
      <p className='text-base'>
        <a href='https://restcountries.com/' target='_blank' rel='noreferrer'>API </a>
        <a href='https://www.frontendmentor.io/challenges/rest-countries-api-with-color-theme-switcher-5cacc469fec04111f7b848ca' target='_blank' rel='noreferrer'>Source</a>
      </p>
    </footer>
  )
}