import { useAppContext } from '../../hooks/useAppContext'

export default function Footer() {
  const context = useAppContext()
  const year = new Date().getFullYear()
  const bgTextClasses = context.isDark ?
    'bg-dark-blue text-very-light-gray' :
    'bg-slate-100 text-very-dark-blue-lm'

  return (
    <footer
      className={`${bgTextClasses} flex flex-col justify-center
       items-center py-2`}
    >
      <p className='text-base sm:text-xl'>
        {`Generated by create next app. ${year}`}
      </p>
      <p className='text-sm sm:text-base'>
        <a href='https://restcountries.com/' target='_blank' rel='noreferrer' className='hover:font-semibold'>API </a>
        <a href='https://www.frontendmentor.io/challenges/rest-countries-api-with-color-theme-switcher-5cacc469fec04111f7b848ca' target='_blank' rel='noreferrer' className='hover:font-semibold'>Source</a>
      </p>
    </footer>
  )
}